import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillGithub,
  AiFillMediumCircle,
  AiFillFacebook,
} from "react-icons/ai";
import deved from "../public/background.webp";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Lakkaru</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl ">
              .developedby<b>ZIJJA</b>
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-xl" />
              </li>
              <li>
                <a
                  href="https://www.lakkaru.com/documents/RB00048%20Lakshman%20Karunasena.pdf"
                  className="bg-cyan-500 text-white px-4 py-2 rounded-2xl ml-4"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Lakshman Karunasena
            </h2>
            <h3 className="text-2xl py-2">Front-End Developer.</h3>
            <p className="leading-8 py-5 text-gray-800">
              "I remain optimistic that with the help of resources such as
              Google, YouTube, ChatGPT, and other supporting platforms as well
              as smart people."
            </p>
          </div>
          <div className="text-5xl justify-center flex py-3 text-gray-600 gap-8">
            <a href="">
              <AiFillYoutube />
            </a>
            <a href="">
              <AiFillTwitterCircle />
            </a>
            <a href="">
              <AiFillLinkedin />
            </a>
            <a href="">
              <AiFillMediumCircle />
            </a>
            <a href="">
              <AiFillGithub />
            </a>
            <a href="">
              <AiFillFacebook />
            </a>
          </div>
          <div className="justify-center flex ">
            <div className=" pb-20 w-80 h-80 pt-10 bg-gradient-to-b from-teal-500 rounded-full my-20">
              <Image
                className="object-contain max-h-72 opacity-g deved"
                src={deved}
              />
            </div>
          </div>
        </section>

        <section>
          <hr />
          <div className="flex lg:flex-row md:flex-row flex-col gap-6">
            <div className="max-w-xl mx-auto">
              <h3 className="text-3xl py-1 mt-5">About Me</h3>
              <p className="text-md  py-2 leading-8  text-gray-800">
                I am a Senior Technical Officer at Sri Lanka Rupavahini
                Corporation and been assigned to the main transmitting station
                at Mount Piduruthalagala.I completed my BIT in the year 2017
                with A- pass on my individual project by self-studying. Even
                though I loved to study in the computer science field, I just
                missed the opportunity to enroll in the USCS with A/L result in
                1996. I got selected for the Industrial Management stream at the
                University of Kelaniya. During this period, I learned Pascal and
                visual basic languages. I used these languages for creating
                small applications for my day-to-day tasks such as transformer
                winding calculations. I automated duty roster generation for
                Piduruthalagala staff in 2012 and still in use with a
                spreadsheet. Also, I practiced and implemented several
                prototypes using Arduino, nodeMCU, and its sensors and modules
                for the remote operation of electronic devices.
              </p>
            </div>
            <hr />
            <div className="max-w-xl mx-auto">
              <h3 className="text-3xl py-1">Skills</h3>
              <p className="text-md  py-2 leading-8  text-gray-800">
                I am a Senior Technical Officer at Sri Lanka Rupavahini
                Corporation and been assigned to the main transmitting station
                at Mount Piduruthalagala.I completed my BIT in the year 2017
                with A- pass on my individual project by self-studying. Even
                though I loved to study in the computer science field, I just
                missed the opportunity to enroll in the USCS with A/L result in
                1996. I got selected for the Industrial Management stream at the
                University of Kelaniya. During this period, I learned Pascal and
                visual basic languages. I used these languages for creating
                small applications for my day-to-day tasks such as transformer
                winding calculations. I automated duty roster generation for
                Piduruthalagala staff in 2012 and still in use with a
                spreadsheet. Also, I practiced and implemented several
                prototypes using Arduino, nodeMCU, and its sensors and modules
                for the remote operation of electronic devices.
              </p>
            </div>
          </div>
        </section>
        <section>
          <div className="border-t-2"></div>
        </section>
      </main>
    </>
  );
}
